param(
    [string]$ProjectDir = $PSScriptRoot,
    [string[]]$Roles = @("manager", "architect", "developer", "developer", "tester", "tester")
)

# vaak team launcher — Layer 1 of the 4-layer always-engaged stack.
# See learn/.vaak/al-architecture-diagram.md §12 (Session Resilience) for the full design.
#
# Per-seat self-healing wrapper:
#   - while-loop catches every claude exit (crash, rate limit, Stop-hook escape, Ctrl+C)
#   - exponential backoff 2,4,8,16,30s (cap); 5 restarts within 60s -> 5min pause
#   - sentinel file `.vaak/stop-<role>-<instance>` triggers graceful drain
#   - --resume <session-id> on subsequent attempts (avoids cwd-shared identity collapse)
#   - drops --resume and re-runs full join prompt at >=200 tool calls or >=4h since last fresh
#   - structured JSONL log at .vaak/logs/<role>-<instance>.jsonl
#   - exports VAAK_ROLE / VAAK_INSTANCE / VAAK_PROJECT_DIR for Layer 3 hooks
#
# Layer 2 (vaak-mcp --supervise) and Layer 3 (PreToolUse/PostToolUse heartbeat hooks)
# are owned by dev:0 and ship separately. This file does not depend on either being live.

# ------- Compute per-role instance numbers -------
$roleCounts = @{}
$seatPlan = @()
foreach ($r in $Roles) {
    if (-not $roleCounts.ContainsKey($r)) { $roleCounts[$r] = 0 }
    $seatPlan += [pscustomobject]@{ role = $r; instance = $roleCounts[$r] }
    $roleCounts[$r]++
}

# ------- Ensure log + session directories exist -------
$logsDir  = Join-Path $ProjectDir ".vaak\logs"
$seatsDir = Join-Path $ProjectDir ".vaak\sessions"
New-Item -ItemType Directory -Force -Path $logsDir  | Out-Null
New-Item -ItemType Directory -Force -Path $seatsDir | Out-Null

foreach ($seat in $seatPlan) {
    $role         = $seat.role
    $instance     = $seat.instance
    $seatLabel    = "$role-$instance"
    $seatJsonPath = Join-Path $seatsDir "$seatLabel.json"
    $logPath      = Join-Path $logsDir  "$seatLabel.jsonl"
    $sentinelPath = Join-Path $ProjectDir ".vaak\stop-$seatLabel"

    $scriptContent = @"
# vaak-launch wrapper for $seatLabel — auto-generated by launch-team.ps1
Set-Location "$ProjectDir"
`$env:VAAK_ROLE         = "$role"
`$env:VAAK_INSTANCE     = "$instance"
`$env:VAAK_PROJECT_DIR  = "$ProjectDir"

`$seatJsonPath = "$seatJsonPath"
`$logPath      = "$logPath"
`$sentinelPath = "$sentinelPath"

function Write-VaakLog(`$ev, `$payload) {
    `$entry = [pscustomobject]@{
        ts      = (Get-Date -Format 'o')
        seat    = "$seatLabel"
        event   = `$ev
        payload = `$payload
    } | ConvertTo-Json -Compress -Depth 6
    try { Add-Content -Path `$logPath -Value `$entry -Encoding UTF8 } catch { }
}

`$initialPrompt = "Join this project as a $role with instance $instance using the mcp__vaak__project_join tool. Then call mcp__vaak__project_wait in a loop to stay available for messages."
`$resumeNudge   = "Re-engage in autonomous team mode. Handle any unread team messages, then call mcp__vaak__project_wait to enter standby. Continue indefinitely."

`$restartTimes = @()
`$attempt = 0

while (`$true) {
    # ---- Escape valve: touch .vaak/stop-<role>-<inst> to drain this seat ----
    if (Test-Path `$sentinelPath) {
        Remove-Item `$sentinelPath -Force -ErrorAction SilentlyContinue
        Write-VaakLog 'sentinel_exit' @{ reason = 'graceful drain via sentinel file' }
        Write-Host "[vaak-launch][$seatLabel] sentinel observed - exiting wrapper" -ForegroundColor Magenta
        break
    }

    `$attempt++
    `$now = Get-Date

    # ---- Sliding-window crash-loop guard: 5 restarts in 60s -> pause 5min ----
    `$restartTimes = @(`$restartTimes | Where-Object { (`$now - `$_).TotalSeconds -lt 60 })
    if (`$restartTimes.Count -ge 5) {
        Write-VaakLog 'crash_loop_pause' @{ recent_restarts = `$restartTimes.Count; pause_secs = 300 }
        Write-Host "[vaak-launch][$seatLabel] crash-looping (5 restarts within 60s). Pausing 300s." -ForegroundColor Red
        Start-Sleep -Seconds 300
        `$restartTimes = @()
    }

    # ---- Decide: fresh launch (initial prompt) vs --resume (re-engage nudge) ----
    `$useResume      = `$false
    `$resumeId       = `$null
    `$reasonFresh    = 'first_launch'
    `$seatData       = `$null

    if (Test-Path `$seatJsonPath) {
        try { `$seatData = Get-Content `$seatJsonPath -Raw -ErrorAction Stop | ConvertFrom-Json } catch { `$seatData = `$null }
    }

    if (`$seatData -ne `$null -and `$attempt -gt 1) {
        `$tools  = if (`$seatData.tool_count_since_fresh) { [int]`$seatData.tool_count_since_fresh } else { 0 }
        `$ageHrs = if (`$seatData.last_fresh_at) { ((`$now - (Get-Date `$seatData.last_fresh_at)).TotalHours) } else { 999 }
        if (`$tools -ge 200) {
            `$reasonFresh = "tool_count_`$tools"
        } elseif (`$ageHrs -ge 4) {
            `$reasonFresh = ("wall_clock_{0:N1}h" -f `$ageHrs)
        } elseif (`$seatData.session_id) {
            `$useResume = `$true
            `$resumeId  = `$seatData.session_id
        }
    }

    Write-Host ''
    Write-Host "[vaak-launch][$seatLabel] attempt `$attempt @ `$(Get-Date -Format 'HH:mm:ss')  use_resume=`$useResume" -ForegroundColor Cyan

    `$exitCode = 0
    if (`$useResume) {
        Write-VaakLog 'claude_resume' @{ session_id = `$resumeId; attempt = `$attempt }
        claude --dangerously-skip-permissions --resume `$resumeId `$resumeNudge
        `$exitCode = `$LASTEXITCODE
    } else {
        # Fresh launch — reset per-seat counters; vaak-mcp hook will write session_id
        Write-VaakLog 'claude_fresh' @{ attempt = `$attempt; reason = `$reasonFresh }
        [pscustomobject]@{
            role                   = '$role'
            instance               = $instance
            session_id             = `$null
            last_fresh_at          = (Get-Date -Format 'o')
            tool_count_since_fresh = 0
            wrapper_pid            = `$PID
            last_active_at_ms      = 0
        } | ConvertTo-Json -Depth 6 | Set-Content -Path `$seatJsonPath -Encoding UTF8

        claude --dangerously-skip-permissions `$initialPrompt
        `$exitCode = `$LASTEXITCODE
    }

    Write-VaakLog 'claude_exit' @{ exit_code = `$exitCode; attempt = `$attempt }
    `$restartTimes += `$now

    # ---- Exponential backoff: 2,4,8,16,30 (cap) ----
    `$backoff = [Math]::Min([Math]::Pow(2, [Math]::Min(`$attempt, 5)), 30)
    Write-Host "[vaak-launch][$seatLabel] claude exited code=`$exitCode. Restarting in `${backoff}s..." -ForegroundColor Yellow
    Start-Sleep -Seconds `$backoff
}
"@

    $tempScript = [System.IO.Path]::Combine($env:TEMP, "vaak-launch-$seatLabel-$(Get-Random).ps1")
    $scriptContent | Out-File -FilePath $tempScript -Encoding UTF8
    Start-Process powershell `
        -WorkingDirectory $ProjectDir `
        -ArgumentList '-NoExit', '-ExecutionPolicy', 'Bypass', '-File', $tempScript
    Start-Sleep -Seconds 2
}

Write-Host ''
Write-Host "Launched $($Roles.Count) team members:" -ForegroundColor Green
foreach ($s in $seatPlan) { Write-Host "  $($s.role):$($s.instance)" }
Write-Host ''

# Slice 8 — Layer 2 supervisor auto-launch (spec §12.2). Spawns vaak-mcp.exe
# --supervise as a detached process so it survives this script exiting.
# Idempotent via supervisor.pid lock with stale-PID recovery — if a previous
# supervisor is alive, the new instance exits cleanly without disrupting it.
$vaakMcpExe = Join-Path $PSScriptRoot 'desktop\src-tauri\binaries\vaak-mcp-x86_64-pc-windows-msvc.exe'
if (Test-Path $vaakMcpExe) {
    Write-Host "Layer 2: starting vaak-mcp --supervise (90s stall → 5s grace → kill+relaunch)..." -ForegroundColor Cyan
    # Detached spawn — survives parent exit. Logs to .vaak/supervisor.log.
    $supervisorLog = Join-Path $ProjectDir '.vaak\supervisor.log'
    Start-Process -FilePath $vaakMcpExe `
        -ArgumentList @('--supervise', '--project-dir', $ProjectDir) `
        -RedirectStandardOutput $supervisorLog `
        -RedirectStandardError $supervisorLog `
        -WindowStyle Hidden `
        -PassThru | Out-Null
    Write-Host "  (supervisor log: $supervisorLog — tails Layer 2 buzz/grace/kill events)" -ForegroundColor DarkGray
} else {
    Write-Host "Layer 2 SKIPPED: $vaakMcpExe not found. Build vaak-desktop first." -ForegroundColor Yellow
}
Write-Host "Layer 3 (Pre/PostToolUse hooks) install via 'vaak-mcp.exe --install-hooks' (idempotent)."
Write-Host "Logs:           $logsDir\<role>-<instance>.jsonl"
Write-Host "Drain a seat:   New-Item $ProjectDir\.vaak\stop-<role>-<instance>"
